#ifndef INC_VESC_UART_H_
#define INC_VESC_UART_H_

#include "main.h"
#include "motor.h"

// VESC Packet start/end bytes
#define VESC_PACKET_START_SMALL 0x02
#define VESC_PACKET_START_LARGE 0x03
#define VESC_PACKET_END         0x03

// VESC Command IDs
typedef enum {
    COMM_FW_VERSION = 0,
    COMM_JUMP_TO_BOOTLOADER,
    COMM_ERASE_NEW_APP,
    COMM_WRITE_NEW_APP_DATA,
    COMM_GET_VALUES,
    COMM_SET_DUTY,
    COMM_SET_CURRENT,
    COMM_SET_BRAKE,
    COMM_SET_RPM,
    COMM_SET_POS,
    COMM_STATS,
    COMM_SET_CURRENT_BRAKE,
    COMM_SET_CURRENT_HANDBRAKE,
    COMM_SET_CURRENT_REL,
    COMM_SET_BRAKE_REL,
    COMM_SET_CURRENT_LIMITS,
    COMM_SET_CURRENT_IN_LIMITS,
    COMM_SET_CURRENT_BRAKE_RELATIVE,
    COMM_SET_CURRENT_BRAKE_IN_RELATIVE,
    COMM_SET_CURRENT_BRAKE_LIMITS,
    COMM_SET_CURRENT_BRAKE_IN_LIMITS,
    COMM_SET_EXTERNAL_BUTTON,
    COMM_GET_EXTERNAL_BUTTON,
    COMM_SET_RTC,
    COMM_GET_RTC,
    COMM_SET_CHUCK_DATA,
    COMM_CUSTOM_APP_DATA,
    COMM_SET_CURRENT_REL_IN,
    COMM_SET_BRAKE_REL_IN,
    COMM_GET_VALUES_SELECTIVE,
    COMM_GET_VALUES_SETUP,
    COMM_SET_MCCONF,
    COMM_GET_MCCONF,
    COMM_GET_MCCONF_DEFAULT,
    COMM_SET_APPCONF,
    COMM_GET_APPCONF,
    COMM_GET_APPCONF_DEFAULT,
    COMM_SAMPLE_PRINT,
    COMM_TERMINAL_CMD,
    COMM_PRINT,
    COMM_ROTOR_POSITION,
    COMM_EXPERIMENT_SAMPLE,
    COMM_DETECT_MOTOR_PARAM,
    COMM_DETECT_MOTOR_R_L,
    COMM_DETECT_MOTOR_FLUX_LINKAGE,
    COMM_DETECT_ENCODER,
    COMM_DETECT_HALL_FOC,
    COMM_REBOOT,
    COMM_ALIVE,
    COMM_GET_DECODED_PPM,
    COMM_GET_DECODED_ADC,
    COMM_GET_DECODED_CHUCK,
    COMM_FORWARD_CAN,
    COMM_SET_CHUCK_DATA_LOCAL,
    COMM_GET_VALUES_SETUP_SELECTIVE,
    COMM_SET_VALUES_SETUP,
    COMM_SET_LISP_STAT,
    COMM_FILL_RX_BUFFER,
    COMM_PROCESS_RX_BUFFER,
    COMM_GET_VALUES_LITE,
    COMM_GET_VALUES_ROLLING,
    COMM_GET_VALUES_SETUP_ROLLING,
    COMM_SET_CURRENT_REL_ROLLING,
    COMM_SET_BRAKE_REL_ROLLING,
    COMM_SET_CURRENT_REL_IN_ROLLING,
    COMM_SET_BRAKE_REL_IN_ROLLING,
    COMM_GET_STATS,
    COMM_SET_STATS,
} VESC_COMM_ID;

void VESC_UART_Init(UART_HandleTypeDef *huart);
void VESC_UART_Process(MotorStatePublic_t *motorState);

#endif /* INC_VESC_UART_H_ */
